name: "docs 📚"
description: "new feature"
labels: "docs 📚"
body:
  - type: textarea
    attributes:
      label: Task ✅
    validations:
      required: true
  - type: textarea
    attributes:
      label: Memo 🚨