name: "fix 🐛"
description: "new feature"
labels: "fix 🐛"
body:
  - type: textarea
    attributes:
      label: Task ✅
    validations:
      required: true
  - type: textarea
    attributes:
      label: Memo 🚨