name: "style 💄"
description: "new feature"
labels: "style 💄"
body:
  - type: textarea
    attributes:
      label: Task ✅
    validations:
      required: true
  - type: textarea
    attributes:
      label: Memo 🚨